### ISSUE TITLE
A CPU benchmark, and request for running VLM on GPU

### ISSUE THREAD

**Issue by tofu-bar** [celll1/tagmane#1]
I was trying to find a suite batch size of CPU inference for my PC. I could run 1-10 batches, but I hope GPU could run it much more and faster... What do you think?

I used the default model, which should be a bit heavy model: wd-eval02-large-tagger-v3

Here's some benchmark result of CPU utilization of batch size 1-4, 10, and idle. I couldn't run 100. 
Runtime was like 1:100%, 2: 80%, 3:60%, 4:60%, 10: 180%

<img width="300" alt="1 スクリーンショット 2024-10-20 004906" src="https://github.com/user-attachments/assets/46561faa-188b-4f8f-88b0-c48da681bc07">
<img width="300" alt="2 スクリーンショット 2024-10-20 004714" src="https://github.com/user-attachments/assets/6ac165b6-1ab6-43c5-ac3f-fc352e3156a2">
<img width="300" alt="3 スクリーンショット 2024-10-20 004515" src="https://github.com/user-attachments/assets/21795083-9a2e-4b6f-9e03-fd1484185c25">
<img width="300" alt="4 スクリーンショット 2024-10-20 005230" src="https://github.com/user-attachments/assets/800fe874-e4e9-41fc-9ace-e6350d67eb9f">
<img width="300" alt="10 スクリーンショット 2024-10-20 005409" src="https://github.com/user-attachments/assets/23537000-40af-4708-b689-fda68adc78df">
<img width="300" alt="0 スクリーンショット 2024-10-20 005537" src="https://github.com/user-attachments/assets/63e1dc14-31fb-47e5-8929-c15ef0aa9eff">

**Comment by celll1** [comment]
I'm including batch settings for future inference using DirectML, but it has not been implemented yet. 
I will work on it after the code is refactored.

**Comment by celll1** [comment]
I have implemented inference on the GPU, so I will close this issue. Thank you for your suggestion.
